### PR TITLE
Migrate to AndroidX and some more changes

### PR DESCRIPTION
**Pull request by flxholle**
I did following:
 - Migrated Project to AndroidX
 - Added instant module support
 - Changed to Start/End properties
 - Removed unused feedback button in navigation drawer
 - Updated libraries

### CODE REVIEW

**Comment by fabianski7** [comment]
@asdoi maybe you could create a fork of this repository and keep this app separate? it looks like the developer won't keep it anymore.

**Comment by flxholle** [comment]
Hi @fabianski7 I already forked this repository and made some bugfixes/enhancements here: https://github.com/asdoi/QuickLyric/tree/my_app
As this app does not receive any updates on f-droid because of Chromaprint, I removed that library (which is currently not completely integrated) and added the old lyric sources.
Furthermore I am working on a pull request, because, as mentioned in the readme, I am not allowed to change the f-droid source link because only QuickLyric is allowed to use the lyric apis, but you could build it yourself.

**Comment by fabianski7** [comment]
> Furthermore I am working on a pull request, because, as mentioned in the readme, I am not allowed to change the f-droid source link because only QuickLyric is allowed to use the lyric apis, but you could build it yourself.

I didn't know that a license was needed to get the lyrics to the songs. on the desktop I use the clementine player that captures lyrics from other sites, I don't think he has any specific license for that. Maybe this is something more related to the source (website), correct? in this case AZLyrics.

I already tried to compile some apps on my computer but it is not fast enough for that. it remains to be expected that someone will accept your PR

**Comment by Babelia13** [comment]
Hi @asdoi 

Do you have new news about the project? The code is so deprecated in master branch. The code version is 3.5.4c, and the last commit is more than 2 years ago, while the Google Play version is 3.9.0c, and it was released 3 months ago :( 

I was working in new optimizations for Android TV but I think the repo owner is not going to update the code in order to allow us contributing to it for the newer versions.

I wrote the owner an email, but i don't have an answer yet.

**Comment by flxholle** [comment]
Hi @Babelia13 
As mentioned above, I created another branch for my personal use (https://github.com/quwepiro/QuickLyric/tree/my_app) where I removed the (unfinished) chromaprint integration and added the old lyrics sources.
You are free to use it for your Android TV optimizations, as the current code is only using one source (LyricsChart) which has a very small database.

Furthermore if I understand this document right: https://github.com/QuickLyric/QuickLyric/wiki/Can-I-fork-this-project,-change-the-name,-put-it-on-Google-Play-and-pretend-it's-mine%3F
the app itself is gpl but only the original QuickLyric app is allowed to use the api keys for the lyric sources.
That is why I did not made a merge request to the f-droid repository.


> Do you have new news about the project?

So no, I think the author decided to not update this repository anymore.

**Comment by geecko86** [comment]
Hey folks! Maintainer here.

First of all, I would like to apologize to everyone here. I believe I owe you all some explanations.

It seems the main topic of conversation in this PR has shifted to "is this project even alive anymore?". It is! But it isn't my main activity anymore and has become less of a priority for me - as you might have guessed.

Just as @Babelia13 pointed out: the public repository (this one) is not being updated too often. I'm hoping I can change this in the coming weeks/months (no promises!). The core issue has always been that proprietary stuff (related to our proprietary API, advertising revenues, lyrics displays, ...) is so tightly integrated in the app that maintaining two separate branches (a free software branch as well as a private branch) is complicated to say the least, especially given that this project is no longer my main occupation.

@asdoi Thank you so much for this PR! I could've sworn I had responded to you back in June. I'm so sorry!

Unfortunately, it seems to have some issues. Just to name one: it seems to be using AndroidX Fragments in some parts but the platform FragmentManager in others. After pulling the code, I'm unable to compile it from scratch. Please let me know what's up with that. Thanks!

The build that's currently on Google Play already has updated libraries as well as AndroidX. The reason I didn't simply close the PR was because you listed the "Instant app support", which is obviously a ton of work and not something I have yet to implement! However, after inspecting your code, it seems you simply used the Android Studio feature located in "Refactor -> Enable Instant app support". Correct me if I'm wrong but I believe there's [a lot more to it](https://medium.com/better-programming/everything-you-should-know-about-instant-apps-on-android-2ea83b18dc8e), including dividing the app into smaller submodules and refactoring permissions.

**For this reason, I will most likely close this PR and update the master branch in the coming days.** Please notify me if you think I'm missing something. Thanks again for your work and sorry for not updating this repository sooner!

Regarding your earlier comment: Chromaprint is Free Software, so no - that's not why the app is not being updated on F-Droid. Instead, the decision was made because of lack of ROI. Spending resources to maintain a GPLv3 version of the app was not something I could afford. But that's a separate discussion.

@fabianski7 

> I didn't know that a license was needed to get the lyrics to the songs. on the desktop I use the clementine player that captures lyrics from other sites, I don't think he has any specific license for that. Maybe this is something more related to the source (website), correct? in this case AZLyrics.

I'm not a lawyer, but I can tell you a license is _absolutely_ required to distribute copyrighted lyrics like this. You wish it wasn't, but it is. Simply because "Clementine Player" hasn't been targeted by the NMPA lawyers yet doesn't make it legal. Instead, it likely has to do with the fact that it's a fairly low profile software.

I do not wish to debate this, 5 years ago (!), QuickLyric was targeted by a DMCA request after a complaint from the NMPA. American copyright law is what it is - that's all I can say.

@Babelia13 I stopped reading the emails a while ago, it got overwhelming and took waaaay too much time. I will 1. Update this repo and 2. Find your email to let you know how you can contribute to the project. I would love to review your contribution! Android TV sounds like a great idea.

----

Please do let me know if you have other questions for me or if I said something wrong. Cheers!

**Comment by flxholle** [comment]
Hi @geecko86 
thank you very much for you explanations.

> **For this reason, I will most likely close this PR and update the master branch in the coming days.** Please notify me if you think I'm missing something. Thanks again for your work and sorry for not updating this repository sooner!

Yes, I just used the Android-Studio button :wink: I thought that would be enough for enabling instant app support.
Furthermore I have reinstalled Android Studio some days ago and I could not sync or build my fork anymore. 

About the f-droid updates, in other projects (like https://github.com/timusus/Shuttle/) there is an extra `f-droid` branch with a feature-less foss version and all f-droid releases are named something like `f-droid-v1.0.0`.
Maybe this is something for this project too, depending on how many non-oss libraries were used (of course I could work on this, if it is not too difficult).

**Comment by Babelia13** [comment]
Hi all! Thank you so much for your comments.

@asdoi, as @geecko86 said, I was unable to build the project from your branch, but finally I did some changes and I was able to do it. Let me know if you want to know the changes I did.

@geecko86 I will wait you to update the code to open my PR. I think is a good idea to include the Android TV support both in the open source code and in your private branch. I think it is a really interesting feature for the users in Google Play! For now, I only solved some bugs using the app in Android TV and I added the controller support for the initial onboarding screens. If you tell me you are going to update the project, I'm excited to continue with support for the rest of the app =)

**Comment by flxholle** [comment]
> but finally I did some changes and I was able to do it. Let me know if you want to know the changes I did.

Yes that would be very nice. I think this is better in a separate issue in my fork: https://github.com/quwepiro/QuickLyric/issues/3
Thank you very much

**Comment by Babelia13** [comment]
Hi all!

I opened a [Pull Request](https://github.com/quwepiro/QuickLyric/pull/4) over the Android X branch in @asdoi repo. When those changes are applied, you can open the PR to this repo again.

Thanks so much

**Pull request closed without merging**
